// ----------------------------------------------------------------------

export const account = {
    displayName: 'Jaydon Frankie',
    email: 'demo@minimals.cc',
    photoURL: '/assets/images/avatars/avatar_25.jpg',
};

export const INVESTMENT_SECTORS = [
    'Advertising',
    'AgTech',
    'AI',
    'Analytics',
    'AR/VR',
    'AudioTech',
    'AutoTech',
    'BioTech',
    'Bockchain / Crypto / Web3',
    'ClimateTech / CealTech',
    'Cloud Computing',
    'Cloud Infrastructure',
    'ConstructioinTech',
    'Consumer Health',
    'Consumer Internet',
    'Cosmetics',
    'Creator Economy',
    'Cyber Security',
    'D2C',
    'Data Services',
    'DeepTech',
    'Developer Tools',
    'Diagnostics',
    'Digital Health',
    'Drug Delivery',
    'E-Commerce',
    'EdTech',
    'EnergyTech',
    'Enterprise',
    'Entertainment & Sports',
    'ESG',
    'FashionTech',
    'FinTech',
    'FoodTech',
    'Feature of Work',
    'Games',
    'Gaming/eSports',
    'Generative Tech',
    'Gig Economy',
    'GovTech',
    'Hardware',
    'HealthTech',
    'Hospitality / Lodging',
    'HRTech / Human Capital',
    'Impact',
    'insurTech',
    'IoT',
    'LegalTech',
    'Local Services',
    'Logistics',
    'Manufacturing',
    'MarketignTech',
    'Marketplaces',
    'Material Science',
    'medical Devices',
    'Mobility',
    'Other',
    'Paas',
    'Parenting & Families',
    'Payments',
    'Pharmaceuticals',
    'Real Estate/Prop Tech',
    'Retail',
    'Robotics',
    'SaaS',
    'Sales & CRM',
    'Security',
    'Semiconductors',
    'Smart Cities / Urban Tech',
    'SMB',
    'Social Commerce',
    'Social Networks',
    'SpaceTech',
    'Supply Chain Tech',
    'Therapecutics',
    'TransportationTech',
    'Travel',
    'VC Funds',
    'Wellness & Fitness',
];

export const DEAL_SIZE = ['0', '1-5', '5-10', '10-15', '15-20', '20-30', '30-40', '50+'];

export const INVESTMENT_SIZE = ['0-$10K', '$10k-$25K', '$25K-$50K', '$50K-$100K', '$100K-$500K', '$500K-$1M', '$1M-$5M', '$5M+'];

export const INVESTMENT_STAGES = [
    'Pre-Seed',
    'Seed',
    'Seed Extension',
    'Series A',
    'Series B',
    'Series C',
    'Series D',
    'Series E',
    'Series F',
    'Series H+',
    'Token Sale (SAFT)',
    'Toke Sale',
    'Secondary Equity',
    'Secondary SAFT',
    'VC Fund',
    'Other',
];

export const GEOGRAPHIES = ['North America', 'Europe', 'Israel', 'MENA', 'LATAM', 'Africa', 'India', 'South East Asia', 'China', 'Centeral Asia', 'Australia'];
